#!/bin/bash

# Download all files attached to a Zenodo record

set -e

# Print input info
usage() {
    echo Downloading Record "$RECORD_ID" to "$DL_DIR"
}
# Report error and exit
perror() {
    echo Error: "$1" >&2
    exit 1
}

# Check if all params are supplied
if [ "$#" -eq 0 ]; then
    perror "Missing parameters"
    exit 1
fi

# Parameters
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -i|--id) RECORD_ID="$2";
            shift;shift;;
        -d|--dir) DL_DIR="$2";
            shift;shift;;
        *) echo Unknown parameter passed: "$1";
            exit 1;
    esac;
    if [[ -z $RECORD_ID ]]; then    
        echo "Error: Record ID must be declared (-i, --id)"
        exit 1
    fi
done

# If download dir is not identified, assign  pwd
if [[ -z $DL_DIR ]]; then
    DL_DIR=`pwd`; 
fi

# Check HTTP status and exit if error
HTTP_STATUS="$(curl -ILs https://zenodo.org/record/"$RECORD_ID" | head -1 | sed -rn 's/HTTP.*([0-9]{3}).*/\1/p')";
if [[ $HTTP_STATUS != 200 ]]; then
    echo Record cannot be reached;
    echo Error \(HTTP: "$HTTP_STATUS"\);
    exit 1
fi

# Main

FILES="$(curl -X GET -s https://zenodo.org/record/"$RECORD_ID" | sed -rn 's/.*href="(\/.*\/files\/.*\?download=1).*/\1/p' | sort -u)"
FILE_NO="$(echo -n "$FILES" | grep -c '^')";

if [[ $FILE_NO -eq 0 ]]; then
    echo No download links found;
    exit 1
fi

echo Found "$FILE_NO" files;

while IFS= read -r line; do
	echo Downloading "$line";
    curl -X GET -OJLR https://zenodo.org"$line";
done <<<$FILES

exit 0
